### DISCUSSION TITLE
opencollective.com

### DISCUSSION THREAD

**Discussion by pocco81** [catppuccin/catppuccin#1846] [Port Requests]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes

**Additional context 📷 (optional)**
Because of https://opencollective.com/catppuccin :heart:

**Comment by WalkQuackBack** [comment]
I don't personally think that this is a viable userstyle anymore, considering that as of the latest update to the site, many elements use generated classes and colours which reroll quite often from me watching over the course of a month.

**Reply by scarcekoi** [reply]
It uses CSS variables now. Do you think it's good to theme now?
```css
@layer base {
  :root {
    --background: var(--color-white);
    --foreground: var(--color-slate-900);
    --card: var(--color-white);
    --card-foreground: var(--color-slate-900);
    --popover: var(--color-white);
    --popover-foreground: var(--color-slate-900);
    --primary: var(--color-blue-600);
    --primary-foreground: var(--color-slate-50);
    --secondary: var(--color-slate-100);
    --secondary-foreground: var(--color-slate-900);
    --muted: var(--color-slate-100);
    --muted-foreground: var(--color-slate-500);
    --accent: var(--color-slate-100);
    --accent-foreground: var(--color-slate-900);
    --destructive: var(--color-rose-500);
    --destructive-foreground: var(--color-slate-50);
    --border: var(--color-slate-200);
    --input: var(--color-slate-200);
    --ring: var(--color-blue-600);
    --radius: .75rem;
  }
}
```
