### DISCUSSION TITLE
CloudTube

### DISCUSSION THREAD

**Discussion by FelicityIris** [catppuccin/catppuccin#1900] [Port Requests]
### Will you make the port?

- [ ] Yes, I'm willing to make the port

### How can the requested port be themed?

Port can be themed using Stylus or Stylish Web Extensions.

### Has the requested port been themed already?

No.

### Any additional comments?

Example Instance of CloudTube in question: https://tube.northboot.xyz/

**Comment by FelicityIris** [comment]
I have written a Mocha Favour Blue Accented version of it with some transition and round corner theming. Unfortunately it has some personalized colours not of the palette but I hope it can still be used as a reference point for someone to modify. Use with Stylus extension.

```css
@-moz-document domain("tube.northboot.xyz") {
body,
input.search {
    background: #1e1e2e !important;
    color: #a0a0ff !important
}

nav.main-nav,
div.channel-data {
    background: #181825;
    color: #a0a0ff
}

a,
a[class^="link home"],
a[class^="link icon"],
a.title-link,
a.author {
    color: #a0a0ff !important;
    background: transparent !important;
    transition: 0.5s
}

a:hover,
a[class^="link home"]:hover,
a[class^="link home"]:hover,
a.title-link:hover,
a.author:hover {
    color: #a6e3a1 !important;
    background: transparent !important;
    transition: 0.5s
}

div.author-line {
    color: #a0a0ff !important
}

input[class^="border-look field-row__input"] {
    background: #181825
}

input.search,
input[class^="border-look field-row__input"] {
    border-color: #181825 !important;
    transition: 0.5s
}
input.search:focus,
input[class^="border-look field-row__input"]:focus {
    border-color: #a0a0ff !important;
    transition: 0.5s
}
::placeholder {
    color: #5050aa
}

h1 {
    color: #7070ff !important
}

button[class^="subscribe-button base-border-look"] {
    background: #f38ba8 !important;
    color: #1e1e2e !important;
    transition: 0.5s
}
button[class^="subscribe-button base-border-look"]:hover {
    background: #f6bedb !important;
    color: #1e1e2e !important;
    transition: 0.5s
}

div.subscribers {
    color: #cdd6f4 !important
}

svg {
    fill: #a0a0ff !important;
    transition: 0.5s
}
svg:hover {
    fill: #a6e3a1 !important;
    transition: 0.5s
}

div.footer__center {
    background: #181825
}

div.description {
    background: #181825 !important
}

aside.related-videos {
    background: #181825 !important
}

div.button-container,
button.border-look,
select.border-look {
    color: #a0a0ff !important;
    background-color: #181825 !important;
    border-color: #181825 !important;
    transition: 0.5s
}
div.button-container:focus,
button.border-look:focus,
select.border-look:focus {
    color: #a0a0ff !important;
    background-color: #181825 !important;
    border-color: #a0a0ff !important;
    transition: 0.5s
}

button.border-look:hover {
    color: #a6e3a1 !important;
    transition: 0.5s
}
a.border-look {
    background-color: #181825 !important;
    border-color: #a0a0ff !important
}

div.encouraging-message {
    background: #181825;
    color: #a0a0ff
}
}
```
