### DISCUSSION TITLE
Instagram

### DISCUSSION THREAD

**Discussion by aman333nolawz** [catppuccin/catppuccin#1949] [Port Requests]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
Catppuccin stylus theme for instagram

**Comment by aman333nolawz** [comment]
Here's my stylus theme for instagram(feel free to improve it and make a repo from it):
```css
:root * {
    --ig-primary-background: 30, 30, 46;
    --ig-primary-text: 205, 214, 244;
    --ig-primary-button: 166, 227, 161;
    --ig-primary-button-hover: 148, 226, 213;

    --web-always-white: 0, 0, 0;

    --ig-link: 166, 227, 161;

    --ig-highlight-background: 69, 71, 90;

    --ig-banner-background: 69, 71, 90;

    --ig-secondary-background: 17, 17, 27;
    --ig-secondary-text: 166, 173, 200;
    --ig-secondary-button: 244, 244, 244;

    --ig-elevated-background: 30, 30, 46;
    --ig-separator: 69, 71, 90;
    --ig-elevated-separator: 69, 71, 90;
    --post-separator: 69, 71, 90;

    --ig-error-or-destructive: 243, 139, 168;
}

svg {
    fill: #cdd6f4;
    stroke: #cdd6f4;
}

svg * {
    stroke: #cdd6f4;
}

svg[aria-label="Instagram"] {
    color: #cdd6f4;
}

svg[aria-label="Instagram"] * {
    stroke: #cdd6f4;
}

._abm4:hover {
    background-color: #313244;
}
```
