### DISCUSSION TITLE
twitter.com

### DISCUSSION THREAD

**Discussion by nyancrimew** [catppuccin/catppuccin#1957] [Port Requests]
**Are you available to help in the creation of this port? 😄 (optional)**
Maybe

**Additional context 📷 (optional)**
It probably shouldn't be too hard to make a catppuccin stylus theme for twitter for someone with a bit of experience.

**Comment by ohxxm** [comment]
Wouldn't the Dark Reader extension be able to this? The extension does have the catppuccin colorscheme built in for usage.

**Comment by unseen-ninja** [comment]
Technically, yes. But making a dedicated theme usually is more precise and thus looks better. I've been looking at this yesterday for a bit, and it seems possible to do – even tho Twitter has some really annoying way to colour things.

Maybe I'll set up something and count on the community to jump in and make it better. :D

**Comment by xor** [comment]
+1 I'd love to use theme for Twitter.

**Comment by unseen-ninja** [comment]
Well, where getting somewhere. slowly but surely. Twitters markup is … annoying, to phrase it mildly. I have no idea how persistant the randomly generated class names are, that's what scares me the most rn.

![image](https://user-images.githubusercontent.com/35840154/189884722-195b9207-2cd0-4a70-bdfb-bb64f9b54766.png)

I've put up the current customisation code in a [Gist](https://gist.github.com/andreasgrafen/7291e9203c4ab4b94baca30b5f154e02). This currently **only works with the dim colour scheme and the purple accent colour** – feel free to give it a test-drive, tho there are def. unstyled areas.

**Comment by nonetrix** [comment]
Seems it has already somewhat broken 

I am not exactly sure how this works but I assume every time a component in whatever framework they use is updated it generates a random ID

I don't know how this can be over come unless someone is willing to check sure it doesn't break and people are willing to update regularly 
![Screenshot 2022-09-21 at 02-49-08 (4) Home _ Twitter](https://user-images.githubusercontent.com/45698918/191446496-5883b6c5-a6dc-4edc-b72a-a8e8d3785b9c.png)

**Comment by RoootTheFox** [comment]
I currently have a theme that looks pretty good
It's still not finished but it is definitely getting there!
![image](https://user-images.githubusercontent.com/78933889/208545027-8a7479ed-8b8d-4fd7-8674-ff25e399c8f9.png)

I can put the source code into a repository or share it here if wanted/needed.

edit: also worth noting that it currently only supports Catppuccin Mocha with Teal as accent color but those can be very easily changed in the CSS since I put them in a variable

**Comment by RoootTheFox** [comment]
And regarding the random CSS IDs - the best bet would be to rely on other element properties such as HTML properties - I am using this to theme some elements that I couldn't figure out how to theme otherwise.
 ```css
[style^="color: rgb(29, 155, 240)"] {
   color: rgb(var(--ct-color-accent)) !important;
}
[style^="background-color: rgb(29, 155, 240)"] {
   background-color: rgb(var(--ct-color-accent)) !important;
}
 ```

**Comment by RoootTheFox** [comment]
Other HTML properties that are unique to a specific element can also be used, such as
 ```css
/* block confirm button */
[data-testid="confirmationSheetConfirm"].r-42olwf {
   background-color: rgb(var(--ct-color-red)) !important;
}
[data-testid="confirmationSheetConfirm"].r-12d83nn {
   /* hover */
   background-color: rgb(var(--ct-color-red), 0.8) !important;
}
[data-testid="confirmationSheetConfirm"].r-oybae9 {
   /* click */
   background-color: rgb(var(--ct-color-red), 0.75) !important;
}
```

Edit: I uploaded my current version on GitHub gist for anyone wanting to try it out: https://gist.github.com/RoootTheFox/ab67a474a01fb312b2aef1e46f0c79a4
