### DISCUSSION TITLE
Jellyfin

### DISCUSSION THREAD

**Discussion by isabelroses** [catppuccin/catppuccin#2260] [Port Requests]
### Will you make the port?

- [ ] Yes, I'm willing to make the port

### How can the suggested port be themed?

Custom CSS (you need to be on the admin of the instance)

### Any additional comments?

I originally created the port in order to submit it to the catppucin org, but now I no longer have the ability to complete it since I no longer run my own instance.
Please contact me if your willing to work on the repo, it should just be some small touches here and there to bring it out of WIP.
https://github.com/isabelroses/jellyfin

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by nekowinston** [comment]
Might be worth noting that https://github.com/catppuccin/theme.park already supplies a generic theme

**Reply by isabelroses** [reply]
That's true, but the original reason the port was made was because sections were missing or poorly themed in terms of contrast.

**Comment by isabelroses** [comment]
I should also note that we could do something similar to the Codeberg port on the userstyles repo, when this is complete to allow theming outside of instance admins.

**Comment by Bush-cat** [comment]
Here's a nice theme that's easy to customize the palette of, it's called [scyfin](https://github.com/loof2736/scyfin), so I inserted some catcuppin mocha Colors.
```css
@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/scyfin-theme.css');
:root {
    --primary-r: 250;
    --primary-g: 179;
    --primary-b: 135;
    --primary-accent-color: rgba(var(--primary-r), var(--primary-g), var(--primary-b), 1.0);
    --secondary-accent-color: rgba(var(--primary-r), var(--primary-g), var(--primary-b), 0.2);
    --outline-color: #21222E;
    --primary-background-color: #1E1E2E;
    --secondary-background-color: #181825;
}
```

I like to make the background pitch black on my OLED devices, to do this add it to the Client Custom CSS code (instead of server-provided CSS)
```css
@import url('https://cdn.jsdelivr.net/gh/loof2736/scyfin@latest/CSS/theme-oled.css');
:root {
    --primary-background-color: #000000;
    --secondary-background-color: #181825;
    --tertiary-background-color: #1E1E2E;
}
```
