### DISCUSSION TITLE
keybr.com

### DISCUSSION THREAD

**Discussion by Magniquick** [catppuccin/catppuccin#2475] [Port Requests]
### Will you make the port?

- [ ] Yes, I'm willing to make the port

### How can the suggested port be themed?

https://www.keybr.com/
It does have an inbuilt dark and light mode, so maybe it isn't that hard ?

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by johnend** [comment]
Tried playing about with this just now actually. I think it might be reasonably difficult. All the classnames are autogenerated, and everything is using basic elements without easy ways to target stuff. It is still possible but it would be very selector heavy I think. It might also be quite tricky to target letters that are "incorrect" without being able to use a class.

**Comment by janTatesa** [comment]
I think I will make this userstyle. You apparently just have to change these bariables 
```css
html[data-color="dark"] {
  --primary-d2: #4d4d4d;
  --primary-d1: #404040;
  --primary: #333;
  --primary-l1: #2e2e2e;
  --primary-l2: #2b2b2b;
  --secondary-d1: #b8b3b3;
  --secondary: #9f9999;
  --secondary-l1: #867f7f;
  --secondary-l2: #6c6666;
  --secondary-f1: #898585;
  --secondary-f2: #747070;
  --accent-d2: #524d4d;
  --accent-d1: #5f5a5a;
  --accent: #6c6666;
  --accent-l1: #797272;
  --accent-l2: #867f7f;
  --error-d1: #b75c5c;
  --error: #9b4545;
  --error-l1: #783535;
  --shadow-color: #00000088;
  --slow-key-color: #8c1818;
  --fast-key-color: #448154;
  --Chart-speed__color: #517460;
  --Chart-accuracy__color: #914331;
  --Chart-complexity__color: #705282;
  --Chart-threshold__color: #834c67;
  --Chart-hist-h__color: #495074;
  --Chart-hist-m__color: #743939;
  --Chart-hist-r__color: #723a74;
  --KeyboardKey-pointer__color: #4ba0f2;
  --pinky-zone-color: #617a58;
  --ring-zone-color: #76772d;
  --middle-zone-color: #977831;
  --left-index-zone-color: #5b6d66;
  --right-index-zone-color: #835d67;
  --thumb-zone-color: #854b44;
  --effort-0-color: #323948;
  --effort-1-color: #303f5d;
  --effort-2-color: #2f4471;
  --effort-3-color: #2d4a86;
}
```
