### DISCUSSION TITLE
TrueNAS CORE/SCALE

### DISCUSSION THREAD

**Discussion by Midou36O** [catppuccin/catppuccin#2634] [Port Requests]
### Will you make the port?

- [ ] Yes, I'm willing to make the port

### How can the suggested port be themed?

Through Stylus, see below.

### Any additional comments?

There are various themes in TrueNAS, which are the following 
![image](https://github.com/user-attachments/assets/49003009-2e51-46a3-975f-fa7794825729)
I haven't searched how this could be done through Stylus or browser side and based on inspect element it doesn't seem like it uses a css file to color things out ?
The CORE version has a custom theme category (which i don't run), the documentation for this is [**here**](https://www.truenas.com/docs/core/13.0/uireference/topmenu/uipreferences/)
The SCALE version however is more restricted as in doesn't have a custom theme manager, just a preset of themes to pick (as shown in the picture earlier). The documentation for this section is [**here**](https://www.truenas.com/docs/scale/24.04/scaleuireference/systemsettings/generalsettingsscreens/) under GUI Settings Screen.

If more info is required or new information appears to come up feel free to update it here!

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by Midou36O** [comment]
After tinkering a bit i found that those variables allows you to change the colors so i made something quick (and also dirty) using the mocha + lavender color palette:
```css
:root {
  --bg1: #1e1e2e !important; /* base */
  --fg1: #cdd6f4 !important; /* text */
  --topbar: #45475a !important; /* lavender */
  --accent: #f9e2af !important; /* yellow */
  --bg2: #181825 !important; /* mantle */
  --fg2: #a6adc8 !important; /* subtext0 */
  --alt-bg1: #313244 !important; /* surface0 */
  --alt-bg2: #45475a !important; /* surface1 */
  --alt-fg1: #f5e0dc !important; /* rosewater */
  --alt-fg2: #f2cdcd !important; /* flamingo */
  --yellow: #f9e2af !important;
  --orange: #fab387 !important;
  --red: #f38ba8 !important;
  --magenta: #cba6f7 !important;
  --violet: #b4befe !important; /* lavender */
  --blue: #89b4fa !important;
  --cyan: #89dceb !important; /* sky */
  --green: #a6e3a1 !important;
  --pink: #f5c2e7 !important;
  --aqua: #94e2d5 !important; /* teal */
  --tomato: #eba0ac !important; /* maroon */
  --teal: #94e2d5 !important;
  --slategray: #6c7086 !important; /* overlay0 */
  --salmon: #f2cdcd !important;
  --primary: #b4befe !important; /* #b4befe */
  --lines: #585b70 !important; /* surface2 */
  --yellow-txt: #11111b !important;
  --orange-txt: #11111b !important;
  --red-txt: #11111b !important;
  --magenta-txt: #11111b !important;
  --violet-txt: #11111b !important;
  --blue-txt: #11111b !important;
  --cyan-txt: #11111b !important;
  --green-txt: #11111b !important;
  --pink-txt: #11111b !important;
  --aqua-txt: #11111b !important;
  --tomato-txt: #11111b !important;
  --teal-txt: #11111b !important;
  --slategray-txt: #ffffff !important;
  --salmon-txt: #11111b !important;
  --black: #11111b !important; /* crust */
  --white: #ffffff !important;
  --grey: #9399b2 !important; /* overlay2 */
  --focus-bg: rgba(122, 122, 122, 0.55) !important;
  --focus-brd: rgba(255, 255, 255, 0.25) !important;
  --primary-txt: #313244 !important;
  --accent-txt: #cdd6f4 !important;
  --highlight: #f5c2e7 !important; /* pink */
  --contrast-darker: #45475a !important;
  --contrast-darkest: #313244 !important;
  --contrast-lighter: #585b70 !important;
  --contrast-lightest: #b4befe !important;
  --primary-lighter: #89b4fa !important; /* blue */
  --topbar-txt: #cdd6f4 !important;
  --accentColors: var(--violet), var(--orange),var(--cyan),var(--blue),
      var(--yellow), var(--magenta),var(--red),var(--green),var(--pink),
      var(--aqua),var(--tomato),var(--teal),var(--slategray),var(--salmon) !important;
}
```

end result is this 
![image](https://github.com/user-attachments/assets/f39be409-8b0e-4baa-8eea-9c002c3864ef)

looks doable, so feel free to implement it the right way that you feel looks correct to you :)
