### ISSUE TITLE
K9s - Kubernetes tui

### ISSUE THREAD

**Issue by JefeDavis** [catppuccin/catppuccin#147]
**Are you available to help in the creation of this port? 😄 (optional)**
Yes, I've put together an initial draft and am open to feedback if anyone has any suggestions

**Additional context 📷 (optional)**
```yml
#Morning
flamingo: &flamingo "#f2cdcd"
mauve: &mauve "#ddb6f2"
pink: &pink "#f5c2e7"
maroon: &maroon "#e8a2af"
red: &red "#f28fad"
peach: &peach "#f8bd96"
yellow: &yellow "#fae3b0"
green: &green "#abe9b3"
teal: &teal "#b5e8e0"
blue: &blue "#96CDFB"
sky: &sky "#89dceb"

#Night
black0: &black0 "#161320"
black1: &black1 "#1a1826"
black2: &black2 "#1e1e2e"
black3: &black3 "#302d41"
black4: &black4 "#575268"
gray0: &gray0 "#6e6c7e"
gray1: &gray1 "#988ba2"
gray2: &gray2 "#c3bac6"
white: &white "#d9e0ee"
lavender: &lavender "#c9cbff"
rosewater: &rosewater "#f5e0dc"
background: &background default

# Skin...
k9s:
  # General K9s styles
  body:
    fgColor: *white
    bgColor: *background
    logoColor: *mauve
  # Command prompt styles
  prompt:
    fgColor: *white
    bgColor: *background
    suggestColor: *blue
  help:
    fgColor: *white
    bgColor: *background
    sectionColor: *green
    keyColor: *blue
    numKeyColor: *maroon
  # ClusterInfoView styles.
  info:
    fgColor: *peach
    sectionColor: *white
  # Dialog styles.
  dialog:
    fgColor: *yellow
    bgColor: *background
    buttonFgColor: *black2
    buttonBgColor: *gray2
    buttonFocusFgColor: *black2
    buttonFocusBgColor: *pink
    labelFgColor: *yellow
    fieldFgColor: *white
  frame:
    # Borders styles.
    border:
      fgColor: *mauve
      focusColor: *lavender
    menu: 
      fgColor: *white
      keyColor: *blue
      # Used for favorite namespaces
      numKeyColor: *maroon
    # CrumbView attributes for history navigation.
    crumbs: 
      fgColor: *black2
      bgColor: *maroon
      activeColor: *flamingo
  #   # Resource status and update styles
    status: 
      newColor: *blue
      modifyColor: *lavender
      addColor: *green
      pendingColor: *peach
      errorColor: *red
      highlightColor: *sky
      killColor: *mauve
      completedColor: *gray1
    # Border title styles.
    title:
      fgColor: *teal
      bgColor: *background
      highlightColor: *pink
      counterColor: *yellow
      filterColor: *green
  views:
    # Charts skins...
    charts:
      bgColor: *background
      chartBgColor: *background
      dialBgColor: *background
      defaultDialColors:
        - *green
        - *red
      defaultChartColors:
        - *green
        - *red
      resourceColors:
        cpu:
          - *mauve
          - *blue
        mem:
          - *yellow
          - *peach
    # TableView attributes.
    table:
      fgColor: *white #Doesn't Work
      bgColor: *background
      cursorFgColor: *black3 # Doesn't Work
      cursorBgColor: *black4 # should be rosewater
      markColor: *rosewater # Doesn't Work
      # Header row styles.
      header:
        fgColor: *yellow
        bgColor: *background
        sorterColor: *sky
    # Xray view attributes.
    xray:
      fgColor: *white #Doesn't Work
      bgColor: *background
      # Need to set this to a dark color since color text can't be changed
      # Ideally this would be rosewater
      cursorColor: *black4
      cursorTextColor: *black2 #Doesn't Work
      graphicColor: *pink
    # YAML info styles.
    yaml:
      keyColor: *rosewater
      colonColor: *sky
      valueColor: *yellow
    # Logs styles.
    logs:
      fgColor: *white
      bgColor: *background
      indicator:
        fgColor: *lavender
        bgColor: *background
```
<img width="1784" alt="Screen Shot 2022-04-25 at 7 21 53 PM" src="https://user-images.githubusercontent.com/14242442/165190317-cdd2b6e9-5de7-4b5c-9033-6881cd6b96b2.png">

<img width="1779" alt="Screen Shot 2022-04-25 at 7 25 04 PM" src="https://user-images.githubusercontent.com/14242442/165190538-100aeebc-7791-435c-9b83-c3acbc1d0004.png">

<img width="1779" alt="Screen Shot 2022-04-25 at 7 31 57 PM" src="https://user-images.githubusercontent.com/14242442/165191038-9e24d66a-b52e-4fd4-a9ad-d515bf4e1644.png">
