### ISSUE TITLE
Overhaul ANSI & Base16 Colours

### ISSUE THREAD

**Issue by justTOBBI** [catppuccin/catppuccin#1961]
A person on [twitter](https://fxtwitter.com/phaazon_/status/1631605104829710336?t=Ta06KoK1JBgCNTGMxOxsEg&s=19) pointed out, that the term colors are broken due to them not having a light variant. We need ctp 2.1 to have more term colors. 
![image](https://user-images.githubusercontent.com/47004621/222765646-cab9a16f-cb36-4725-8a2c-4f11316c7ce3.png)

**Comment by backwardspy** [comment]
i know @extremepayne was looking into this a little while back, where did you get to with it?

**Comment by nekowinston** [comment]
Yeah, I've been complaining about this issue too since June last year. I think it's fair to say its a known issue, and something we want to address. It will impact other ports though, not just terminal emulators.

Ports that come to mind:
- Every terminal emulator, of course
- IDEs/code editors with a Terminal function (JetBrains/VSCode, etc.)
- TUI/CLI without truecolor support
  - Newsboat
  - GitUI
  - mc

I'm pretty sure there are more CLI tools that lack truecolor support, but those 3 are the first that come to mind.

**Comment by extremepayne** [comment]
> i know @extremepayne was looking into this a little while back, where did you get to with it?

Sorry for missing this ping; got lost in my inbox. I do have a set of colors I decided to use and I recorded them all in [my fork of the alacritty port](https://github.com/extremepayne/catppuccin-alacritty) (chosen because I find the config format readable; i don't actually use alacritty). I'll put the macchiato colors (commented) here.

```yaml
    # Normal colors
    normal:
        black: "#494D64" # surface1
        red: "#ED8796" # red
        green: "#A6DA95" # green
        yellow: "#F5A97F" # peach
        blue: "#8AADF4" # blue
        magenta: "#C6A0F6" # muave
        cyan: "#8BD5CA" # teal
        white: "#B8C0E0" # subtext1

    # Bright colors
    bright:
        black: "#5B6078" # surface2
        red: "#EE99A0" # maroon
        green: "#ADD9A8" # green but bright
        yellow: "#EED49F" # yellow
        blue: "#7DC4E4" # sapphire
        magenta: "#F5BDE6" # pink
        cyan: "#91D7E3" # sky
        white: "#A5ADCB" # subtext0
```
This hits most of the colors and keeps to the names they are given as part of the sixteen. It's missing rosewater, flamingo, and lavender, and it has a modified green simply because ctp has more reddish-purple and fewer green colors than the ANSI 16. Y'all would know better than me which colors are important to represent, I chose the ones I thought looked best. I'm also not certain if I've chosen the right direction for which ones are bright (peach and mauve certainly have more impact than yellow and pink, imo, so should those be bright?). But overall I think the pairings make sense and bring some differentiation to the terminal. I've been using this for a couple weeks and think it works great.
