### ISSUE TITLE
shadcn-ui

### ISSUE THREAD

**Issue by Tnixc** [catppuccin/catppuccin#2270]
### Link to repository

https://github.com/Tnixc/shadcn-ui/tree/main

### Screenshots

![preview](https://github.com/catppuccin/catppuccin/assets/85466117/da9f7c52-571c-498e-992d-1bf95208761a)

### Any additional comments?

It's a bunch of css variables in the proper format. I think I chose the values properly, but please review the choice of colors as I can change it easily. Also all the values that are the same are based on shadcn/ui's default.

### Submission Guidelines

- [X] I have read and followed Catppuccin's submission guidelines.

**Comment by errorcodezero** [comment]
This looks really cool. I hope this gets added to the catppuccin org

**Comment by Tnixc** [comment]
Thanks. I'm not really sure what this is waiting on right now.

**Comment by uncenter** [comment]
I just gave it a review and it looks fine to me!

**Comment by sgoudham** [comment]
Just quickly taking a look at the preview, is there any reason for the `Save Changes` button to be red compared to the blue ones?

The default example on their website seems to indicate that it should all be one colour?
![image](https://github.com/catppuccin/catppuccin/assets/58985301/2081badd-cf29-4000-89ec-1fc15dd0271f)

**Comment by uncenter** [comment]
I'm not sure where the preview screenshots are from but it looks fine to me when I apply the variables to the [shadcn/ui examples](https://ui.shadcn.com/examples/cards):

```less
/* ==UserStyle==
@name           ui.shadcn.com
@namespace      shadcn/ui
@version        0.1.0
==/UserStyle== */

@-moz-document domain("ui.shadcn.com") {
  :root,
  :root.dark {
    --background: 229.091 18.644% 23.137%; /* base */
    --foreground: 227.234 70.149% 86.863%; /* text */

    --muted: 230 15.584% 30.196%; /* surface0 */
    --muted-foreground: 226.667 43.689% 79.804%; /* subtext1 */

    --popover: 229.091 18.644% 23.137%; /* base */
    --popover-foreground: 227.234 70.149% 86.863%; /* text */

    --card: 229.091 18.644% 23.137%; /* base */
    --card-foreground: 227.234 70.149% 86.863%; /* text */

    --border: 227.143 14.737% 37.255%; /* surface1 */
    --input: 227.143 14.737% 37.255%; /* surface1 */

    --primary: 276.667 59.016% 76.078%; /* mauve */
    --primary-foreground: 229.091 18.644% 23.137%; /* base */

    --secondary: 230 15.584% 30.196%; /* surface0 */
    --secondary-foreground: 227.234 70.149% 86.863%; /* text */

    --accent: 230 15.584% 30.196%; /* surface0 */
    --accent-foreground: 227.234 70.149% 86.863%; /* text */

    --destructive: 358.812 67.785% 70.784%; /* red */
    --destructive-foreground: 230.526 18.812% 19.804%; /* mantle */

    --ring: 227.234 70.149% 86.863%; /* text */

    --radius: 0.5rem;
  }
}
```
